---
name: Build

on:
  push:
    branches: [ "master", "main" ]
    tags: [ 'v*.*.*', 'v*.*.*-*' ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create archive
        run: tar -czvf gopass-otp-linux.tar.gz gopass-otp _gopass-otp

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: gopass-otp-linux.tar.gz


